[package]
name = "ammonia"
version = "0.3.0"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html" ]
license = "MIT / Apache-2.0"
readme = "README.md"
documentation = "https://www.notriddle.com/rustdoc/ammonia/index.html"
repository = "https://github.com/notriddle/ammonia"

[features]
unstable = [ "html5ever/unstable", "tendril/unstable" ]

[dependencies]
html5ever = "0.13"
html5ever-atoms = "0.2"
maplit = "0.1"
tendril = "0.2"
url = "1.4"
